version: 2.1
executors:
  node10:
    docker:
      - image: circleci/node:10
        environment:
          NPM_CONFIG_PREFIX: "~/.npm-global"
    working_directory: ~/repo

commands:
  setup:
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: install npm 6.13.4
        command: sudo npm -g install npm@6.13.4
    - run:
        name: Installing Dependencies
        command: npm ci
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: prepare test git user
        command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node10

    steps:
    - setup
    - run: mkdir junit
    - run:
        name: Lint
        command: npm run lint

    # test & get code coverage
    - run:
        name: Getting Code Coverage
        command: circleci tests glob test/test*.js | circleci tests split --split-by=timings | xargs ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- -R mocha-junit-reporter --exit && npx codecov
        environment:
          MOCHA_FILE: junit/test-results.xml

    - store_test_results:
        path: junit

    - store_artifacts:
        path: junit

  release:
    executor: node10

    steps:
    - setup

    - run:
        name: revert changes to package-lock.json
        command: git checkout -- package-lock.json

    - run:
        name: Semantic Release
        command: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
    - build
    - release:
        context: Project Helix
        requires:
        - build
        filters:
          branches:
            only: master
